---

- name: Install WireGuard
  include_tasks: install.yml

- name: Configure WireGuard
  include_tasks: configure.yml

- name: IP forwarding sysctl
  include_tasks: sysctl.yml

- name: WireGuard service
  include_tasks: service.yml
  when: ansible_facts['os_family'] != "Alpine"

- name: WireGuard service (Alpine)
  include_tasks: service_alpine.yml
  when: ansible_facts['os_family'] == "Alpine"
