---

- name: IPv4/IPv6 forwarding sysctls
  ansible.builtin.template:
    src: sysctl.conf.j2
    dest: "{{ wg_sysctl_path }}"
    mode: '0700'
    owner: root
    group: root
  when: wg_sysctl == True
  notify: Apply sysctl

- name: Remove IPv4/IPv6 forwarding sysctls
  ansible.builtin.file:
    path: "{{ wg_sysctl_path }}"
    state: absent
  when: wg_sysctl == False

# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_handlers.html#id4
- name: Run handlers now
  ansible.builtin.meta: flush_handlers
