---

- name: sysctl
  shell: "sysctl -p {{ wg_sysctl_path }}"

# This doesn't work - potential fix @ https://rolflekang.com/ansible-handlers-in-loops
- name: restart interface
  service:
    name: "wg-quick@{{ item.name }}"
    state: restarted
  when: (item.started | bool) | default(wg_interface_started)
