---

- name: Apply sysctl
  ansible.builtin.command: "sysctl -p {{ wg_sysctl_path }}"

- name: Restart interfaces
  loop: "{{ wg_if_list.results | selectattr('changed', 'equalto', true) | map(attribute='item') | list }}"
  ansible.builtin.service:
    name: "wg-quick@{{ item.interface }}"
    state: restarted
  when: (item.started | bool) | default(wg_interface_started)
  loop_control:
    label: "{{ item.interface }}"
